package com.otilm.api.model.connector.signatures.formatting;

import com.otilm.api.model.client.signing.profile.workflow.SigningWorkflowType;
import com.otilm.api.model.common.enums.cryptography.DigestAlgorithm;
import com.otilm.api.model.common.enums.cryptography.SignatureAlgorithm;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotNull;
import java.math.BigInteger;
import java.time.Duration;
import java.time.Instant;
import java.util.List;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

/**
 * DTBS formatting request for the Timestamping workflow.
 *
 * <p>
 * Carries Core-generated fields required for TSTInfo construction: {@code serialNumber} (recorded in the Signature
 * inventory), {@code signingTime} (captured from the time quality system) and {@code accuracy} (captured from the time
 * quality system).
 * </p>
 *
 * <p>
 * The timestamping-specific fields declared here are duplicated in {@link TimestampingFormatResponseRequestDto}.
 * {@code TimestampingDtoFieldParityTest} enforces that shared fields have identical Java types and annotation types
 * across the two DTOs.
 * </p>
 */
@Data
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
@Schema(title = "TimestampingFormatDtbsRequestDto", description = "DTBS formatting request for Timestamping")
public class TimestampingFormatDtbsRequestDto extends FormatDtbsRequestDto {

    @NotNull
    @Schema(description = "Serial number generated by Core, recorded in the Signature inventory",
            requiredMode = Schema.RequiredMode.REQUIRED)
    private BigInteger serialNumber;

    @NotNull
    @Schema(description = "Signing time captured by Core from the time quality system",
            requiredMode = Schema.RequiredMode.REQUIRED, type = "string", format = "date-time",
            example = "2024-05-01T12:00:00Z")
    private Instant signingTime;

    @Schema(description = "Accuracy of the signing time, captured by Core from the time quality system (ISO 8601 duration, e.g. PT0.001S for 1 ms). "
            + "Optional per RFC 3161 — absent when no Time Quality Configuration applies (e.g. a non-qualified local-clock timestamp).",
            requiredMode = Schema.RequiredMode.NOT_REQUIRED, type = "string", example = "PT0.001S")
    private Duration accuracy;

    @NotNull
    @Schema(description = "Signature algorithm to be used for timestamping",
            requiredMode = Schema.RequiredMode.REQUIRED)
    private SignatureAlgorithm signatureAlgorithm;

    @NotNull
    @Schema(description = "Hash algorithm used to produce the message imprint in the timestamp request",
            requiredMode = Schema.RequiredMode.REQUIRED)
    private DigestAlgorithm hashAlgorithm;

    @Schema(description = "TSA policy OID requested by the client")
    private String policy;

    @Schema(description = "Nonce from the timestamp request for replay protection")
    private BigInteger nonce;

    @Schema(description = "Whether the signer certificate should be included in the response",
            requiredMode = Schema.RequiredMode.REQUIRED)
    private boolean includeSignerCertificate;

    @Schema(description = "Whether the timestamp is ETSI qualified electronic timestamp",
            requiredMode = Schema.RequiredMode.REQUIRED)
    private boolean qualifiedTimestamp;

    @Schema(description = "Extensions from the timestamp request")
    private List<ExtensionDto> requestExtensions;

    public TimestampingFormatDtbsRequestDto() {
        super(SigningWorkflowType.TIMESTAMPING);
    }
}
